# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QApplication, QDialog, QDialogButtonBox, QFormLayout, QLineEdit


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 950)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        
        # MainWindow.showMaximized()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(0, -30, 1366, 1000))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("black_bg.jpeg"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(390, 840, 581, 71))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("output-onlinegiftools.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(430, 190, 521, 501))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("output-onlinegiftools (1).gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(130, 40, 231, 121))
        self.bg_2.setText("")
        self.bg_2.setPixmap(QtGui.QPixmap("Start.png"))
        self.bg_2.setScaledContents(True)
        self.bg_2.setObjectName("bg_2")
        self.startbutton = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(140, 60, 211, 91))
        self.startbutton.setStyleSheet("background-color: transparent;")
        self.startbutton.setText("")
        self.startbutton.setObjectName("startbutton")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(1050, 50, 211, 111))
        self.bg_3.setText("")
        self.bg_3.setPixmap(QtGui.QPixmap("Quit.png"))
        self.bg_3.setScaledContents(True)
        self.bg_3.setObjectName("bg_3")
        self.quitbutton = QtWidgets.QPushButton(self.centralwidget)
        self.quitbutton.setGeometry(QtCore.QRect(1050, 60, 201, 91))
        self.quitbutton.setStyleSheet("background-color:transparent;")
        self.quitbutton.setText("")
        self.quitbutton.setObjectName("quitbutton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(420, 740, 501, 61))
        self.textBrowser.setStyleSheet("background-color:transparent;")
        self.textBrowser.setObjectName("textBrowser")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(370, 700, 601, 141))
        self.bg_4.setText("")
        self.bg_4.setPixmap(QtGui.QPixmap("download.jpg"))
        self.bg_4.setScaledContents(True)
        self.bg_4.setObjectName("bg_4")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(350, 10, 711, 171))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("initial.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
